# Generated by Django 4.0.1 on 2022-02-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imgurl',
            field=models.ImageField(blank=True, default='/image0.jpg', null=True, upload_to=''),
        ),
    ]
