# Generated by Django 4.0.1 on 2022-02-03 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_post_imgurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
